#!/usr/bin/env bash

set -eu
mkdir -p /opt/android/toolchains

target_arch=$1

case "$target_arch" in
    "arm64")
        export llvm_arch="aarch64-linux-android"
        ;;
    "x86_64")
        export llvm_arch="x86_64-linux-android"
        ;;
    "arm")
        export llvm_arch="arm-linux-androideabi"
        ;;
    "x86")
        export llvm_arch="i686-linux-android"
        ;;
esac

/opt/android/android-ndk-r20/build/tools/make-standalone-toolchain.sh \
  --platform=android-21 \
  --arch=$target_arch \
  --install-dir=/opt/android/toolchains/android21-$target_arch \
  1>&2

for lib in crtbegin_dynamic.o crtend_android.o crtbegin_so.o crtend_so.o; do
    ln -s "/opt/android/toolchains/android21-${target_arch}/sysroot/usr/lib/${llvm_arch}/21/$lib" \
          "/opt/android/toolchains/android21-${target_arch}/sysroot/usr/lib/${llvm_arch}/" \
          1>&2
done

ANDROID_TOOLCHAIN_ROOT="/opt/android/toolchains/android21-${target_arch}"
ANDROID_SYSROOT="${ANDROID_TOOLCHAIN_ROOT}/sysroot"
ANDROID_C_COMPILER="${ANDROID_TOOLCHAIN_ROOT}/bin/${llvm_arch}-clang"

# outputing environment variables to be used for this toolchain
echo export ANDROID_TOOLCHAIN_ROOT="\"$ANDROID_TOOLCHAIN_ROOT\""
echo export ANDROID_SYSROOT="\"$ANDROID_SYSROOT\""
echo export ANDROID_C_COMPILER="\"$ANDROID_C_COMPILER\""
